name: Run Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install colorama

      - name: Run regex tests
        run: python3 tests/regex.py